baseurl      = "http://thesipham1401.github.io"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "IoT and Networking Engineer || Amateur Photographer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "I'm Thesi"
    subtitle = "Stories of My Life"
    keywords = ""
    copyright = '<a href="https://github.com/thesipham1401" target="_blank" rel="noopener">thesipham1401</a> - <a href="https://www.facebook.com/qkiena14" target="_blank" rel="noopener">Quốc Kiên</a>'


    [languages.en.params.logo]
      logoText = "$ cd /thesi/home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog/"


  [[menu.main]]
  identifier = "project"
  name       = "Project"
  url        = "/project/"
  [[menu.main]]
  identifier = "story"
  name       = "Story"
  url        = "/story/"
